### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules  
  - _src
  - package.json
  - package-lock.json
  - webpack.config.js
  - .prettierrc.json
  - docker-compose.yml
  - README.md