site_name: allartk.github.io
site_url: https://allartk.github.io
theme:
  name: material
  features:
    - content.code.copy
plugins:
  - blog
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences